config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'omniauths#create'
  get 'auth/failure', to: redirect('/')
  get '/signup', to: 'users#new'
  resources :users do
    resources :orders
    get '/orders/:id', to: 'orders#edit'
    delete '/orders/:item_id', to: 'orders#destroy'
  end
  resources :products
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  get '/404', to: 'application#page_not_found', as: '/not_found'
  namespace :admin do
    root 'base#index'
    resources :users, :categories, :auctions, :orders
    resources :products do
      resources :timers
    end
    get '/sale/:id', to: 'status_products#sale', as: '/sale'
    get '/unsale/:id', to: 'status_products#unsale', as: '/unsale'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :items
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :find_order, only: %i[edit update show destroy]

  def index
    if params[:content].blank? and params[:status].blank? and params[:"date-start"].blank? and params[:"date-end"].blank?
      @orders = Order.paginate(page: params[:page], per_page: 10).order('id DESC')
    else
      content = params[:content]
      status = params[:status]
      if params[:"date-end"].blank?
        if params[:"date-start"].blank?
          @orders = Order.search_with_out_time(content, status).paginate(page: params[:page], per_page: 10).order('id DESC')
        else
          date_start = params[:"date-start"].to_time
          @orders = Order.search_start_time(content, status, date_start).paginate(page: params[:page], per_page: 10).order('id DESC')
        end
      else
        date_end = params[:"date-end"].to_time
        if params[:"date-start"].blank?
          @orders = Order.search_end_time(content, status, date_end).paginate(page: params[:page], per_page: 10).order('id DESC')
        else
          date_start = params[:"date-start"].to_time
          @orders = Order.search(content, status, date_start, date_end).paginate(page: params[:page], per_page: 10).order('id DESC')
        end
      end
      byebug
    end
  end

  def show
    @items = @order.items.paginate(page: params[:page], per_page: 20)
  end

  def edit; end

  def update
    if @order.update_attributes(order_params)
      flash[:success] = 'Update success'
      redirect_to admin_orders_path
    else
      render :edit
    end
  end

  def destroy
    if check_delete_order @order
      if @order.destroy
        flash[:success] = 'Delete success'
      else
        flash[:notice] = 'Delete error'
      end
    else
      flash[:notice] = 'Please wait for order checkout'
    end
    redirect_to admin_orders_path
  end

  def delete_more_order
    if request.post?
      if params[:ids]
        delete_ids = []
        params[:ids].each do |id|
          if check_delete_order Order.find(id.to_i)
            delete_ids << id.to_i
          else
            redirect_to admin_orders_path, notice: 'Please wait for order checkout'
          end
        end
        unless delete_ids.empty?
          delete_ids.each do |id|
            Order.find(id).destroy
          end
          redirect_to admin_orders_path, notice: 'Delete success'
        end
      end
    end
  end

  private

    def find_order
      @order = Order.find_by(id: params[:id]) || redirect_to_not_found
    end

    def order_params
      params.require(:order).permit(%i[status type_payment])
    end

    def check_delete_order(order)
      return true if order.status == 'received'
      false
    end
end

app/controllers/orders/cancels_controller.rb
class Orders::CancelsController < ApplicationController
  def update
    order = Order.find(params[:id])
    order.update_columns(status: Order::STATUS_CANCLED)
    flash[:success] = 'Cancel success'
    redirect_to my_orders_path(current_user)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order, only: %i[index destroy edit update total_quantity]

  def index
    @items = @order.items if @order
  end

  def destroy
    @item = Item.find_by(id: params[:id])
    @item.destroy
    redirect_to user_orders_path
  end

  def edit; end

  def update
    if @order.update_attributes(order_params)
      @order.update_attributes(status: 'checkouted')
      redirect_to root_path, notice: 'Success'
    else
      render :edit
    end
  end

  private

    def order_params
      params.require(:order).permit(%i[name address phone])
    end

    def find_order
      @order = Order.find_by(user_id: current_user.id, status: 'wait')
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_order.html.erb
<tr class="odd gradeX">
  <td class="center"><%= order.id %></td>
  <td class="center"><%= link_to order.user.name , '#', class: 'detail-item' %></td>
  <td class="center"><%= order.address %></td>
  <td class="center"><%= order.phone %></td>
  <td class="center"><%= order.total_price %></td>
  <td class="center"><%= order.status %></td>
  <td class="center">
    <%= link_to 'Delete', admin_order_path(order), method: :delete, class: 'button-item delete-item btn-margin',
                          data: { confirm: "You sure?" } %>
    <%= link_to 'Detail', admin_order_path(order), class: 'button-item update-item' %> 
  </td>
</tr>

app/views/admin/orders/edit.html.erb
<% provide(:manage, 'Manage Order') %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p>Update Order</p>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-6">
            <%= form_for(@order, url: admin_order_path) do |f| %>
              <%= form_group_for f, :name, label: false  do %>
                <div class="form-group">
                  <%= f.label :name %>
                  <%= f.text_field :name, placeholder: @order.name, readonly: :true, class: 'form-control' %>
                </div>
              <% end %>
              <%= form_group_for f, :address, label: false  do %>
                <div class="form-group">
                  <%= f.label :address %>
                  <%= f.text_field :address, placeholder: @order.address, readonly: :true, class: 'form-control' %>
                </div>
              <% end %>
              <%= form_group_for f, :phone, label: false  do %>
                <div class="form-group">
                  <%= f.label :phone %>
                  <%= f.text_field :phone, placeholder: @order.phone, readonly: :true, class: 'form-control' %>
                </div>
              <% end %>
              <%= form_group_for f, :status, label: false  do %>
                <div class="form-group">
                  <%= f.label(:status, 'Status:' ) %>
                  <%= f.select(:status, options_for_select(["wait","checkouted","delivered", "received"], selected: @order.status), {}, { class: 'form-control col-3' }) %>
                </div>
              <% end %>
              <%= form_group_for f, :type_payment, label: false  do %>
                <div class="form-group">
                  <%= f.label(:type_payment, 'Type Payment:')%>
                  <%= f.select(:type_payment, options_for_select(["Cash on delivery","Ngan Luong"], selected: @order.type_payment), {}, { class: 'form-control col-3' }) %>
                </div>
              <% end %>              
              <%= f.submit "Submit", class: 'btn btn-success' %>
              <%= f.submit "Reset", class: 'btn btn-warning', type: 'reset' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<% provide(:manage, 'Manage Order') %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p>List Orders</p>
      </div>
      <div class="panel-body">
        <table width="100%" class="table table-striped table-hover" id="dataTables-example">
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Address</th>
              <th>Phone</th>
              <th>Total Price</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
            <tbody>
              <%= render @orders %>
          </tbody>
        </table>
        <%= will_paginate %>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<% provide(:manage, 'Order Detail') %>
<p>Name: <%= @order.user.name %></p>
<p>Address: <%= @order.address %></p>
<p>Phone: <%= @order.phone %></p>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p>List Item</p>
      </div>
      <div class="panel-body">
        <div class='header-panel-body'>
        </div>
        <table width="100%" class="table table-striped table-hover" id="dataTables-example">
          <thead>
            <tr>
              <th class="center">#</th>
              <th class="center">Name</th>
              <th class="center">Amount</th>
            </tr>
          </thead>
            <tbody>
              <%= render @items %>
              <tr>
                <td colspan="2">Total Price</td>
                <td class="center"><%= @order.total_price %></td>
              </tr>  
          </tbody>
        </table>
        <%= will_paginate @items %>
      </div>
    </div>
  </div>
</div>