config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'omniauths#create'
  get 'auth/failure', to: redirect('/')
  get '/signup', to: 'users#new'
  resources :users do
    resources :orders
    get '/orders/:id', to: 'orders#edit'
    delete '/orders/:item_id', to: 'orders#destroy'
  end
  resources :products
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  get '/404', to: 'application#page_not_found', as: '/not_found'
  namespace :admin do
    root 'base#index'
    resources :users, :categories, :auctions, :orders
    resources :products do
      resources :timers
    end
    get '/sale/:id', to: 'status_products#sale', as: '/sale'
    get '/unsale/:id', to: 'status_products#unsale', as: '/unsale'
  end
end

app/views/layouts/admin/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <a class="navbar-brand" href="/admin">Autions Admin</a>
  </div>
  <ul class="nav navbar-top-links navbar-right" id='nav-right'>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li><%= link_to raw('<i class="fa fa-user fa-fw"></i> User Profile'), edit_admin_user_path(current_user) %></li>
        <li class="divider"></li>
        <li><%= link_to raw('<i class="fa fa-sign-out fa-fw"></i> Logout'), logout_url, method: :delete %></li>
        </li>
      </ul>
    </li>
  </ul>
  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li class="sidebar-search">
          <div class="input-group custom-search-form">
            <input type="text" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">
                <i class="fa fa-search"></i>
              </button>
            </span>
          </div>
        </li>
        <li>
          <%= link_to raw('<i class="fa fa-dashboard fa-fw"></i> Dashboard'), admin_root_path %>
        </li>
        <li>
          <a href="#"><i class="fa fa-user fa-fw"></i> Users<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to raw('<i class="fa fa-plus fa-fw"></i> Add user'), new_admin_user_path %>
            </li>
            <li>
              <%= link_to raw('<i class="fa fa-bank fa-fw"></i> Manage users'), admin_users_path %>
            </li>
          </ul>
        </li>
        <li>
          <a href="#"><i class="fa fa-sitemap fa-fw"></i> Categories<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to raw('<i class="fa fa-plus fa-fw"></i> Add category'), new_admin_category_path %>
            </li>
            <li>
              <%= link_to raw('<i class="fa fa-bank fa-fw"></i> Manage categories'), admin_categories_path %>
            </li>
          </ul>
        </li>
        <li>
          <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Products<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to raw('<i class="fa fa-plus fa-fw"></i> Add product'), new_admin_product_path %>
            </li>
            <li>
              <%= link_to raw('<i class="fa fa-bank fa-fw"></i> Manage products'), admin_products_path %>
            </li>
          </ul>
        </li>
        <li>
          <a href="#"><i class="fa fa-files-o fa-fw"></i> Autions<span class="fa arrow"></a>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to "Manage Auction", admin_auctions_path %>
            </li>
          </ul>
        </li>
        <li>
          <a href="#"><i class="fa fa-table fa-fw"></i> Orders<span class="fa arrow"></a>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to "Manage Orders", admin_orders_path %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Autions Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <div id="wrapper">
        <%= render 'layouts/admin/nav' %>
        <div id="page-wrapper">
            <div class="row">
              <div class="col-lg-12">
                <h1 class="page-header"><%= yield(:manage) %></h1>
              </div>
            </div>
            <% flash.each do |message_type, message| %>
              <div class="alert alert-success col-sm-3"><%= message %></div>
            <% end %>
            <%= yield %>
        </div>
    </div>
  </body>
</html>