config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'omniauths#create'
  get 'auth/failure', to: redirect('/')
  get '/signup', to: 'users#new'
  resources :users do
    resources :orders
    get '/orders/:id', to: 'orders#edit'
    delete '/orders/:item_id', to: 'orders#destroy'
  end
  resources :products
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  get '/404', to: 'application#page_not_found', as: '/not_found'
  namespace :admin do
    root 'base#index'
    resources :users, :categories, :auctions, :orders
    resources :products do
      resources :timers
    end
    get '/sale/:id', to: 'status_products#sale', as: '/sale'
    get '/unsale/:id', to: 'status_products#unsale', as: '/unsale'
  end
end

app/models/timer.rb
class Timer < ApplicationRecord
  before_destroy :delete_redis
  belongs_to :product
  has_many :auctions, dependent: :destroy

  validates :start_at, presence: true
  validates :end_at, presence: true, after: :start_at
  validates :period, presence: true
  validates :bid_step, presence: true
  validates :status, presence: true

  def delete_redis
    $redis.del(self.id)
  end
end

app/controllers/admin/timers_controller.rb
class Admin::TimersController < Admin::BaseController
  before_action :find_product
  before_action :find_timer, only: %i[edit update destroy]

  def index
    @timers = @product.timers
  end

  def new
    @timer = @product.timers.build
  end

  def create
    @timer = @product.timers.new(timer_params)
    return redirect_to(admin_product_timers_path) if @timer.save
    render :new
  end

  def update
    return redirect_to admin_product_timers_path, notice: 'Update success' if @timer.update_attributes(timer_params)
    render :edit
  end

  def destroy
    return redirect_to admin_product_timers_path, notice: 'Delete timer success' if @timer.destroy
    flash[:alert] = 'Delete error'
  end

  private

    def timer_params
      params.require(:timer).permit(%i[start_at end_at period status bid_step])
    end

    def find_product
      @product = Product.find_by(id: params[:product_id]) || redirect_to_not_found
    end

    def find_timer
      @timer = Timer.find_by(id: params[:id]) || redirect_to_not_found
    end
end

app/helpers/admin/timers_helper.rb
module Admin::TimersHelper
end

app/views/admin/timers/_form.html.erb
<%= form_group_for 'col-lg-12', f, :start_at, label: false  do %>
  <div class="form-group">
    <%= f.label :start_at %>
    <br>
    <%= f.time_select :start_at, {include_seconds: true, default: {hour: '00', minute: '00', second: '00'}}, { class: 'form-control-static' } %>
  </div>
<% end %>
<%= form_group_for 'col-lg-12', f, :end_at, label: false  do %>
  <div class="form-group">
    <%= f.label :end_at %>
    <br>    
    <%= f.time_select :end_at, {include_seconds: true, default: {hour: '00', minute: '00', second: '00'}}, { class: 'form-control-static' } %>
  </div>
<% end %>
<%= form_group_for 'col-lg-12', f, :period, label: false  do %>
  <div class="form-group">
    <%= f.label :period %>
    <br>    
    <%= f.time_select :period, { include_seconds: true, default: {hour: '00', minute: '00', second: '00'}}, { class: 'form-control-static' } %>
  </div>
<% end %>
<%= form_group_for 'col-lg-12', f, :bid_step, label: false  do %>
  <div class="form-group">
    <%= f.label :bid_step %>
    <%= f.number_field :bid_step, class: 'form-control' %>
  </div>
<% end %>
<div class="form-group">
  <%= f.label :status %>
  <br>
  <% if @timer.is_running %>
    <%= f.radio_button :is_running, true, checked: true %> 
    <%= label :status_on, 'On' %>
    <%= f.radio_button :is_running, false %>
    <%= label :status_off, 'Off' %>
  <% else %>
    <%= f.radio_button :is_running, true %> 
    <%= label :status_on, 'On' %>
    <%= f.radio_button :is_running, false, checked: true %>
    <%= label :status_off, 'Off' %>
  <% end %>
</div>
<%= f.submit "Submit", class: 'btn btn-success' %>
<%= f.submit "Reset", class: 'btn btn-warning', type: 'reset' %>

app/views/admin/timers/_timer.html.erb
<tr class="odd gradeX">
  <td class="center"><%= timer.id %></td>
  <td class="center"><%= timer.start_at %></td>
  <td class="center"><%= timer.end_at %></td>
  <td class="center"><%= timer.period %></td>
  <td class="center"><%= timer.bid_step %></td>
  <% if timer.status == 'on' %>
    <td class="center status-on"><%= timer.status %></td>
  <% else %>
    <td class="center status-off"><%= timer.status %></td>
  <% end %>
  <td class="center">
    <%= link_to 'Update', edit_admin_product_timer_path(@product, timer), class: 'button-item update-item' %> 
    <%= link_to 'Delete', admin_product_timer_path(@product, timer), method: :delete, class: 'button-item delete-item',
                        data: { confirm: "You sure?" } %>
  </td>
</tr>

app/views/admin/timers/edit.html.erb
<% provide(:manage, 'Manage Timers') %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p>Edit Timer</p>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-6">
            <%= form_for(@timer, url: admin_product_timer_path) do |f| %>
              <%= render 'form', f: f %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/timers/index.html.erb
<% provide(:manage, 'Manage Timers') %>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p>List timers</p>
      </div>
      <div class="panel-body">
        <div class='header-panel-body'>
          <%= link_to 'Add timer', new_admin_product_timer_path(@product), class: 'button-item add-item' %>
          <%= form_tag '#', class: 'col-lg-3', id: 'search'  do %>
            <%= search_field_tag 'name', '', { class: 'form-control', placeholder: 'Search' } %>
          <% end %>
        </div>
        <table width="100%" class="table table-striped table-hover" id="dataTables-example">
          <thead>
            <tr>
              <th class="center">#</th>
              <th class="center">Start at</th>
              <th class="center">End at</th>
              <th class="center">Period</th>          
              <th class="center">Bid Step</th>
              <th class="center">Status</th>
              <th class="center">Action</th>
            </tr>
          </thead>
          <tbody>
            <%= render @timers %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/timers/new.html.erb
<% provide(:manage, 'Manage Timer') %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p>Add Timer</p>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-6">
            <%= form_for(@timer, url: admin_product_timers_path) do |f| %>
              <%= render 'form', f: f %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>