config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'omniauths#create'
  get 'auth/failure', to: redirect('/')
  get '/signup', to: 'users#new'
  resources :users do
    resources :orders
    get '/orders/:id', to: 'orders#edit'
    delete '/orders/:item_id', to: 'orders#destroy'
  end
  resources :products
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  get '/404', to: 'application#page_not_found', as: '/not_found'
  namespace :admin do
    root 'base#index'
    resources :users, :categories, :auctions, :orders
    resources :products do
      resources :timers
    end
    get '/sale/:id', to: 'status_products#sale', as: '/sale'
    get '/unsale/:id', to: 'status_products#unsale', as: '/unsale'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :timers
  has_many :assets, as: :module, dependent: :destroy
  accepts_nested_attributes_for :assets, allow_destroy: true
  has_many :item
  validates :name, presence: true, length: { maximum: 100 }
  validates :detail, presence: true
  validates :quantity, presence: true
  validates :price, presence: true
  validates :price_at, presence: true
  validates :assets, length: { minimum: 1, maximum: 4 }

  def change_status_to_sale
    self.update_attribute(:status, ProductStatus::SELLING)
  end

  def change_status_to_unsale
    self.update_attribute(:status, ProductStatus::UNSELLING)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :find_product, only: %i[show edit update destroy]
  before_action :load_categories, only: %i[new create edit update]

  def index
    @products = Product.paginate(page: params[:page], per_page: 10).order('id DESC')
  end

  def new
    @product = Product.new
    @product.assets.build
  end

  def show
    @assets = @product.assets
  end

  def create
    @product = Product.new(product_params)
    byebug
    @product.status = ProductStatus::SELLING
    return redirect_to admin_products_url, notice: 'Add product success' if @product.save
    render :new
  end

  def edit; end

  def update
    return redirect_to admin_products_path, notice: 'Update success' if @product.update_attributes(product_params)
    render :edit
  end

  def destroy
    @product.destroy
    redirect_to admin_products_url, notice: 'Product deleted'
  end

  private

    def product_params
      params.require(:product).permit(:name, :category_id, :detail, :price,
                                      :price_at, :quantity, assets_attributes:
                                      %i[id file_name _destroy])
    end

    def find_product
      @product = Product.find_by(id: params[:id]) || redirect_to_not_found
    end

    def load_categories
      @categories = Category.all
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def image_first_of_object(product)
    product.assets.first.file_url
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_asset_fields.html.erb
<div class='image-item'>
  <%= form_group_for "col-lg-12", f, :file, label: false  do %>
    <div class="form-group">
      <%= f.label :Image %>
      <%= f.file_field :file, id: "profile-img" %>
      <% if f.object.file_url.present? %>
        <%= image_tag(f.object.file_url, class: "img-resize", id: "profile-img-tag") %>
      <% else %>
        <img src="/product-default.png" id="profile-img-tag" class="img-resize" />
      <% end %>
    </div>
  <% end %>
  <%= f.hidden_field :_destroy, value: 'false' %>
  <%= link_to "Remove Image", '#', onClick: "removeField(this); return false;", class: "btn btn-danger remove" %>
</div>

app/views/admin/products/_form.html.erb
<%= form_group_for f, :name, label: false  do %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
  </div>
<% end %>
<%= form_group_for f, :name, label: false  do %>
  <div class="form-group">
    <%= f.label(:category_id, 'Category:')%>
    <%= f.select(:category_id, options_for_select(@categories.collect{ |u| [u.name, u.id] }, selected: @product.category_id), { prompt: 'Choose category' }, { class: 'form-control' } ) %>
  </div>
<% end %>
<%= form_group_for f, :detail, label: false  do %>
  <div class="form-group">
    <%= f.label :detail %>
    <%= f.text_area :detail, :size => "50x10", placeholder: 'Detail', class: 'form-control' %>
  </div>
<% end %>
<%= form_group_for f, :price, label: false  do %>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, placeholder: 'Price', class: 'form-control' %>
  </div>
<% end %>
<%= form_group_for f, :quantity, label: false  do %>
  <div class="form-group">
    <%= f.label :quantity %>
    <%= f.number_field :quantity, placeholder: 'Quantity', class: 'form-control' %>
  </div>
<% end %>
<%= form_group_for f, :price_at, label: false  do %>
  <div class="form-group">
    <%= f.label :price_at %>
    <%= f.number_field :price_at, placeholder: 'Price start at', class: 'form-control' %>
  </div>
<% end %>
<%= form_group_for f, :assets, label: false  do %>
<% end %>
<div class="image-list">
  <%= f.fields_for :assets do |asset| %>
    <%= render "asset_fields", f: asset %>
  <% end %>
</div>
<%= link_to_add_fields("Add picture", f, :assets) %>
<%= f.submit "Submit", class: 'btn btn-success' %>
<%= f.submit "Reset", class: 'btn btn-warning', type: 'reset' %>

app/views/admin/products/_product.html.erb
<tr class="odd gradeX">
  <td class="center"><%= product.id %></td>
  <td class="center"><%= link_to product.name, admin_product_path(product), class: 'detail-item' %></td>
  <td class="center"><%= parent_name(product.category_id) %></td>
  <td class="center"><%= image_tag image_first_of_object(product), class: 'img-resize' %></td>
  <td class="center col-sm-3"><div class="more"><%= product.detail %></div></td>
  <td class="center"><%= product.price %></td>
  <td class="center"><%= product.quantity %></td>
  <td class="center"><%= product.price_at %></td>
  <td class="center">
    <%= link_to 'Manage Timer', admin_product_timers_path(product), class: 'button-item update-timer-item' %> 
    <%= link_to 'Update', edit_admin_product_path(product), class: 'button-item update-item' %> 
    <%= link_to 'Delete', admin_product_path(product), method: :delete, class: 'button-item delete-item',
                        data: { confirm: "You sure?" } %>
  </td>
</tr>

app/views/admin/products/_sale.html.erb
<%= link_to 'Sale', admin_sale_path(product.id), class: 'btn' %>

app/views/admin/products/_status.html.erb
<% if product.status == 'selling' %>
  <%= render 'unsale', product: product %>
<% else %>
  <%= render 'sale', product: product %>
<% end %>

app/views/admin/products/_unsale.html.erb
<%= link_to 'UnSale', admin_unsale_path(product.id) %>

app/views/admin/products/edit.html.erb
<% provide(:manage, 'Manage Products') %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p>Update Product</p>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <%= form_for(@product, url: admin_product_path) do |f| %>
              <%= render 'form', f: f %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/index.csv.erb
<%- attributes = ['id', 'category_id', 'name', 'price', 'price_at', 'quantity'] -%>
<%= CSV.generate_line attributes %>
<%- @products.each do |product| -%>
  <%- record = attributes.map { |attribute| product.send(attribute) } -%>
  <%= CSV.generate_line(record) -%>
<%- end -%>

app/views/admin/products/index.html.erb
<% provide(:manage, 'Manage products') %>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p>List Products</p>
      </div>
      <div class="panel-body">
        <div class='header-panel-body'>
          <%= link_to 'Add product', new_admin_product_path, class: 'button-item add-item' %>
          <%= form_tag '#', class: 'col-lg-3', id: 'search'  do %>
            <%= search_field_tag 'name', '', { class: 'form-control', placeholder: 'Search' } %>
          <% end %>
        </div>
        <table width="100%" class="table table-striped table-hover" id="dataTables-example">
          <thead>
            <tr>
              <th class="center">#</th>
              <th class="center">Name</th>
              <th class="center">Category</th>
              <th class="center">Picture</th>              
              <th class="center">Detail</th>
              <th class="center">Price</th>
              <th class="center">Quantity</th>
              <th class="center">Price start</th>
              <th class="center">Action</th>
            </tr>
          </thead>
          <tbody>
            <%= render @products %>
          </tbody>
        </table>
        <%= will_paginate %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% provide(:manage, 'Manage Products') %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p>Add Product</p>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <%= form_for(@product, url: admin_products_path) do |f| %>
              <%= render 'form', f: f %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<% provide(:manage, 'Manage products') %>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p>Detail Product</p>
      </div>
      <div class="panel-body">
        <p>Name: <%= @product.name %></p>
        <p>Category: <%= parent_name(@product.category_id) %></p>
        <p>Detail: <%= raw @product.detail %></p>
        <p>Price: <%= @product.price %></p>
        <p>Quantity: <%= @product.quantity %></p>
        <p>Status: <%= @product.status %></p>
        <p>Price start: <%= @product.price_at %></p>
        <p>Picture:</p>
        <%= render @product.assets %>
      </div>
    </div>
  </div>
</div>